# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# tiny6410. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that tiny6410 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.


# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
DEVICE_PACKAGE_OVERLAYS += device/friendlyarm/tiny6410/overlay

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES += \
    device/friendlyarm/tiny6410/egl.cfg:system/lib/egl/egl.cfg \
    device/friendlyarm/tiny6410/vold.fstab:system/etc/vold.fstab \
    device/friendlyarm/tiny6410/asound.conf:system/etc/asound.conf \
    device/friendlyarm/tiny6410/media_profiles.xml:system/etc/media_profiles.xml

# Init files
PRODUCT_COPY_FILES += \
    device/friendlyarm/tiny6410/init.rc:root/init.rc \
    device/friendlyarm/tiny6410/init.tiny6410.rc:root/init.tiny6410.rc \
    device/friendlyarm/tiny6410/ueventd.tiny6410.rc:root/ueventd.tiny6410.rc \
    device/friendlyarm/tiny6410/recovery.rc:root/recovery.rc

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
    device/friendlyarm/tiny6410/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl

# Generated kcm keymaps
PRODUCT_PACKAGES := \
    gpio-keys.kcm

# Misc other modules
PRODUCT_PACKAGES += \
    lights.tiny6410

# Libs
PRODUCT_PACKAGES += \
    copybit.s3c6410 \
    gralloc.s3c6410 \
    libGLES_fimg

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
    frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
    frameworks/base/data/etc/android.hardware.touchscreen.multitouch.distinct.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# Used by BusyBox
KERNEL_MODULES_DIR:=/lib/modules

# Enable Windows Media if supported by the board
WITH_WINDOWS_MEDIA:=true

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
    ro.opengles.version=65537

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       dalvik.vm.heapsize=32m \
       dalvik.vm.dexopt-data-only=1 \

# Extended JNI checks
# The extended JNI checks will cause the system to run more slowly, but they can spot a variety of nasty bugs 
# before they have a chance to cause problems.
# Default=true for development builds, set by android buildsystem.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.kernel.android.checkjni=0 \
    dalvik.vm.checkjni=false

# Screen density is actually considered a locale (since it is taken into account
# the the build-time selection of resources). The product definitions including
# this file must pay attention to the fact that the first entry in the final
# PRODUCT_LOCALES expansion must not be a density.
PRODUCT_LOCALES := mdpi

# Kernel (just a dummy to allow building otapackages)
LOCAL_KERNEL := device/friendlyarm/tiny6410/kernel.dummy
PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
$(call inherit-product-if-exists, vendor/friendlyarm/tiny6410/tiny6410-vendor.mk)
